export const travelTopics = [
  {
    id: 1,
    title: "혼자 여행하는 팁",
    category: "솔로 여행",
    destination: "전 세계",
  },
  {
    id: 2,
    title: "동남아시아의 최고의 해변",
    category: "해변",
    destination: "동남아시아",
  },
  {
    id: 3,
    title: "저예산 여행지 Top 10",
    category: "저예산 여행",
    destination: "전 세계",
  },
  {
    id: 4,
    title: "유럽 로드 트립 일정",
    category: "로드 트립",
    destination: "유럽",
  },
  {
    id: 5,
    title: "몰디브의 럭셔리 리조트",
    category: "럭셔리",
    destination: "몰디브",
  },
  {
    id: 6,
    title: "남아메리카 배낭여행",
    category: "배낭여행",
    destination: "남아메리카",
  },
  {
    id: 7,
    title: "아이들과 함께하는 여행",
    category: "가족 여행",
    destination: "전 세계",
  },
  {
    id: 8,
    title: "일본에서의 문화 체험",
    category: "문화 여행",
    destination: "일본",
  },
  {
    id: 9,
    title: "알프스의 최고의 하이킹 코스",
    category: "모험 여행",
    destination: "알프스",
  },
  {
    id: 10,
    title: "음식을 즐기는 여행: 최고의 미식 여행지",
    category: "미식 여행",
    destination: "전 세계",
  },
  {
    id: 11,
    title: "페루의 고대 유적 탐험",
    category: "역사 여행",
    destination: "페루",
  },
  {
    id: 12,
    title: "뉴욕 시티 가이드",
    category: "도시 여행",
    destination: "뉴욕",
  },
  {
    id: 13,
    title: "스위스 알프스에서 스키 여행",
    category: "겨울 여행",
    destination: "스위스",
  },
  {
    id: 14,
    title: "에코 프렌들리 여행지",
    category: "지속 가능한 여행",
    destination: "전 세계",
  },
  {
    id: 15,
    title: "그리스의 섬 여행",
    category: "섬 여행",
    destination: "그리스",
  },
  {
    id: 16,
    title: "해외 자원봉사 여행",
    category: "자원봉사",
    destination: "전 세계",
  },
  {
    id: 17,
    title: "최고의 여행 사진 촬영지",
    category: "사진 여행",
    destination: "전 세계",
  },
  {
    id: 18,
    title: "발리에서의 허니문 계획",
    category: "로맨틱 여행",
    destination: "발리",
  },
  {
    id: 19,
    title: "미국 국립공원 탐험",
    category: "자연 여행",
    destination: "미국",
  },
  {
    id: 20,
    title: "전 세계의 최고의 축제",
    category: "문화 이벤트",
    destination: "전 세계",
  },
  {
    id: 21,
    title: "모로코 사막에서의 모험",
    category: "모험 여행",
    destination: "모로코",
  },
  {
    id: 22,
    title: "카리브해에서의 요트 여행",
    category: "요트 여행",
    destination: "카리브해",
  },
  {
    id: 23,
    title: "스코틀랜드 성 탐험",
    category: "역사 여행",
    destination: "스코틀랜드",
  },
  {
    id: 24,
    title: "최고의 사파리 여행지",
    category: "야생동물 여행",
    destination: "아프리카",
  },
  {
    id: 25,
    title: "디지털 노마드를 위한 최고의 장소",
    category: "노마드 라이프",
    destination: "전 세계",
  },
  {
    id: 26,
    title: "혼자 여행하기 좋은 호스텔",
    category: "솔로 여행",
    destination: "전 세계",
  },
  {
    id: 27,
    title: "노르웨이의 피오르드 탐험",
    category: "자연 여행",
    destination: "노르웨이",
  },
  {
    id: 28,
    title: "가벼운 여행 가방 꾸리기 팁",
    category: "여행 팁",
    destination: "전 세계",
  },
  {
    id: 29,
    title: "반려동물과 함께 여행하기 좋은 곳",
    category: "반려동물 여행",
    destination: "전 세계",
  },
  {
    id: 30,
    title: "호주의 그레이트 배리어 리프 탐험",
    category: "해양 여행",
    destination: "호주",
  },
  {
    id: 31,
    title: "프랑스 와인 투어",
    category: "미식 여행",
    destination: "프랑스",
  },
  {
    id: 32,
    title: "쇼핑하기 좋은 도시",
    category: "도시 여행",
    destination: "전 세계",
  },
  {
    id: 33,
    title: "인도에서의 문화 탐험",
    category: "문화 여행",
    destination: "인도",
  },
  {
    id: 34,
    title: "아이슬란드의 화산 탐험",
    category: "모험 여행",
    destination: "아이슬란드",
  },
  {
    id: 35,
    title: "비수기에 여행하기",
    category: "저예산 여행",
    destination: "전 세계",
  },
  {
    id: 36,
    title: "미국 최고의 로드 트립",
    category: "로드 트립",
    destination: "미국",
  },
  {
    id: 37,
    title: "네덜란드 자전거 투어",
    category: "모험 여행",
    destination: "네덜란드",
  },
  {
    id: 38,
    title: "지중해 크루즈 여행",
    category: "크루즈 여행",
    destination: "지중해",
  },
  {
    id: 39,
    title: "이탈리아의 예술과 박물관 투어",
    category: "문화 여행",
    destination: "이탈리아",
  },
  {
    id: 40,
    title: "호주의 사막 로드 트립",
    category: "모험 여행",
    destination: "호주",
  },
  {
    id: 41,
    title: "태국의 길거리 음식 탐방",
    category: "미식 여행",
    destination: "태국",
  },
  {
    id: 42,
    title: "동유럽의 숨겨진 여행지",
    category: "비밀 여행지",
    destination: "동유럽",
  },
  {
    id: 43,
    title: "이집트의 역사적 유적지 탐방",
    category: "역사 여행",
    destination: "이집트",
  },
  {
    id: 44,
    title: "멕시코 가족 친화적인 리조트",
    category: "가족 여행",
    destination: "멕시코",
  },
  {
    id: 45,
    title: "밤문화를 즐기기 좋은 도시",
    category: "도시 여행",
    destination: "전 세계",
  },
  {
    id: 46,
    title: "케냐 사파리 체험",
    category: "야생동물 여행",
    destination: "케냐",
  },
  {
    id: 47,
    title: "캄보디아의 사원 탐방",
    category: "문화 여행",
    destination: "캄보디아",
  },
  {
    id: 48,
    title: "주말 여행하기 좋은 도시",
    category: "도시 여행",
    destination: "전 세계",
  },
  {
    id: 49,
    title: "로키 산맥 탐험",
    category: "자연 여행",
    destination: "캐나다/미국",
  },
  {
    id: 50,
    title: "세계 최고의 기차 여행",
    category: "기차 여행",
    destination: "전 세계",
  },
  {
    id: 51,
    title: "스페인 미식 투어",
    category: "미식 여행",
    destination: "스페인",
  },
  {
    id: 52,
    title: "프라하의 역사적 도시 탐방",
    category: "역사 여행",
    destination: "체코",
  },
  {
    id: 53,
    title: "노르웨이 오로라 관측 여행",
    category: "자연 여행",
    destination: "노르웨이",
  },
  {
    id: 54,
    title: "스코틀랜드 고성에서의 하룻밤",
    category: "역사 여행",
    destination: "스코틀랜드",
  },
  {
    id: 55,
    title: "뉴질랜드 모험 여행",
    category: "모험 여행",
    destination: "뉴질랜드",
  },
  {
    id: 56,
    title: "미국 동부 해안 로드 트립",
    category: "로드 트립",
    destination: "미국",
  },
  {
    id: 57,
    title: "캐나다 록키 산맥 하이킹",
    category: "모험 여행",
    destination: "캐나다",
  },
  {
    id: 58,
    title: "일본 전통 온천 여행",
    category: "문화 여행",
    destination: "일본",
  },
];
